### ISSUE TITLE
Repl example broken

### ISSUE THREAD

**Issue by ken-diep** [jaebradley/basketball_reference_web_scraper#183]
Your repl at https://repl.it/@jaebradley/v400api-examples doesn't seem to be working.

I think repl has stopped using requirements.txt in favour of pyproject.toml or the built-in package manager. However, I couldn't get either of these to work after an hour of struggling. Could it be a problem with the package itself on repl?

**Comment by jaebradley** [comment]
@ken-diep it could very well be - lemme update the `repl`.

Thanks for opening this issue - documentation is important!

**Comment by jaebradley** [comment]
@ken-diep the issue was that `repl.it` didn't seem to be able to install `lxml@4.25` so I upgraded it to the latest (`4.5.1`) in #187 and published a patch update with the updated `lxml` version (https://github.com/jaebradley/basketball_reference_web_scraper/releases/tag/4.9.2).

In #190 I should have added updated `repl` links for each API method.

Let me know if that's still not working.
